### ISSUE TITLE
Breaking Dimensional Dungeons

### ISSUE THREAD

**Issue by Joshernoob** [Darkhax-Minecraft/BadMobs#60] opened 2021-12-21 20:34 UTC
![Capture](https://user-images.githubusercontent.com/64944433/146993025-703d0cc9-e6a4-417b-bd72-0cf80685c873.PNG)
Bad Mob Version: BadMobs-1.16.5-9.0.3.jar
Dimensional Dungeons Version: dimdungeons-1.13.1.jar
Forge Version-36.2.20
Pack- Magic Sky

As seen in the pic the author of Dimensional Dungeons found the problem to be unregistering the mobs it was trying to pull. they stated any other way of doing this would fixed the current bug.

Bug: seems bug is that when Dimensional Dungeons cant spawn its Dungeons making massive errors until this mod is turned off

**Comment by Darkhax** [comment] 2021-12-21 22:16
Hello, 

This mod does not unregister any mobs so their analysis of the situation is completely wrong. I simply cancel the mob spawning events as the API permits. I am more than happy to look into the issue if you provide more information such as logs and stacktraces.

**Comment by Joshernoob** [comment] 2021-12-24 22:41
https://pastebin.com/agNaerrs this log that was given to me not full log just part about the mods from what i was told if needed i can request a full one from the person that reported the mod conflict to me

**Comment by Darkhax** [comment] 2021-12-27 02:24
Thanks for providing me with the log, the issue is very clearly on the part of DimDungeons. I will detail the issue so it can be relayed to them and properly fixed by the author of DimDungeons.

The bad logic in their mod originates [here](https://github.com/AllenSeitz/DimDungeons/blob/master/src/main/java/com/catastrophe573/dimdungeons/structure/DungeonPlacementLogicBasic.java#L397). EntityType#spawn is a nullable method and will return null when the spawning of a mob was prevented. DimDungeons does not practice proper null safety with this code and will attempt to modify mobs that did not spawn which results in the crash.

To reiterate what I said in my earlier message, my mod does not unregister the mobs and has never done this. This mod operates through the proper APIs and is in line with what Forge provides. Any mods using these events to cancel spawning will have the same compatibility issues with DimDungeons and a fix is needed on their part.

**Closed as completed by Darkhax** 2021-12-27 02:24 UTC
