### ISSUE TITLE
Internal Server Error on joining smp server

### ISSUE THREAD

**Issue by lukiono** [Darkhax-Minecraft/BadMobs#7] opened 2017-11-20 16:53 UTC
Greetings, 

Every player cant connect to the smp server with BadMobs.

Mod Version: 0.23
Forge Version: 14.23.0.2549
Foamfix 0.8.1 Anarchy also used

Error report (IP was removed manually):
https://ybin.me/p/034da065d6d51fcd#oDeihMol2DC/uZ1PhGZTzYsdxKhAxgzCeS/ZHeaLHYc=

Everything works fine with mod version 0.22

Kind regards

**Comment by darkhax** [comment] 2017-11-20 18:01
Thanks for the report. This is an easy fix, and should be fixed promptly. Note that this is a duplicate of #6 so look there for further updates on your issue.

**Closed** 2017-11-20 18:01 UTC
Labels: bug, duplicate
